global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
#
#  - job_name: 'node-exporter'
#    static_configs:
#      - targets: ['localhost:9090']
#
#  - job_name: 'postgres'
#    static_configs:
#      - targets: ['localhost:9090']
#
#  - job_name: 'kafka'
#    static_configs:
#      - targets: ['localhost:9090']

  - job_name: 'core-crm'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'core-crm:8080' ]
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        replacement: 'core-crm-application'