global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'core-crm'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'core-crm:8080' ]
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        replacement: 'core-crm-application'

  - job_name: 'price-history'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'price-history:8084' ]
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        replacement: 'price-history-application'

  - job_name: 'content-processor'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'content-processor:8082' ]
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        replacement: 'content-processor-application'

  - job_name: 'notification-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'notification-service:8085' ]
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        replacement: 'notification-service-application'

  - job_name: 'content-loader-adapter'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'content-loader-adapter:8081' ]
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        replacement: 'content-loader-adapter-application'