apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-crm
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-crm
  template:
    metadata:
      labels:
        app: core-crm
    spec:
      containers:
        - name: core-crm
          image: core-crm:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service.crm-system.svc.cluster.local:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: core-crm-service
  namespace: crm-system
spec:
  selector:
    app: core-crm
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP