apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-loader-adapter
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-loader-adapter
  template:
    metadata:
      labels:
        app: content-loader-adapter
    spec:
      containers:
        - name: content-loader-adapter
          image: content-loader-adapter:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9094"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: content-loader-adapter-service
  namespace: crm-system
spec:
  selector:
    app: content-loader-adapter
  ports:
    - port: 8081
      targetPort: 8081