apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-processor
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-processor
  template:
    metadata:
      labels:
        app: content-processor
    spec:
      containers:
        - name: content-processor
          image: content-processor:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service.crm-system.svc.cluster.local:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9094"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: content-processor-service
  namespace: crm-system
spec:
  selector:
    app: content-processor
  ports:
    - port: 8082
      targetPort: 8082